title: Eagles Analytics Blog
description: A data-driven look at the Philadelphia Eagles using NFL stats, analytics, and AI.
author: Ansh Saxena
baseurl: "" # leave blank unless you're publishing under a subpath
url: "https://anshs101.github.io" # replace YOUR_USERNAME

theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
